$(document).ready(function()
{
    $('#no').click(function()
    {
        $('#podlogka').addClass("hint"); 
        $('#podlogka').removeClass("open_block");
    });
    $('#delete').click(function()
    {
        $('#podlogka').addClass("open_block"); 
        $('#podlogka').removeClass("hint");
    });
});